### ISSUE TITLE
Initiale Geometrie wird überschrieben

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#1]
# Erwartetes Verhalten
Initiales geojson im `value` des hidden Inputs wird ausgelesen und im LayerTree als Ordner "Zeichnung" im Layer "Zeichnung" angezeigt.

# Beobachtetes Verhalten
Die Standardkonfiguration wird geladen, ohne einen Ordner "Zeichnung".

# Ursache
Der Grund liegt vermutlich hier:

```javascript
Client.js, Z.51 ff.
                                       ...
					self.createModules();
					self.load();
					self.invoke( netgis.Events.CONTEXT_UPDATE, self.config );
                                        ...
```
In `self.load()` wird der Ordner und zugehörige Layer "Zeichnung" noch erzeugt und initial in den LayerTree gelegt. Durch den invoke des Events `CONTEXT_UPDATE` passiert jedoch folgendes:
```javascript
MapOpenLayers.js, Z.768 ff.

netgis.MapOpenLayers.prototype.onContextUpdate = function( e )
{
	this.clearAll();
...
```
Damit wird der OpenLayers Client vollständig geleert und der editierbare Zeichnungslayer geht verloren. 

## Zusatz
Wird `this.clearAll()` auskommentiert, bleibt der "Zeichnungs" Ordner und Layer zwar im LayerTree sichtbar, rendert jedoch keine Geometrie in OpenLayers. Wird dann nochmal ein weiteres Polygon ins Blaue hinein gezeichnet, wird ein weiterer "Zeichnung" Layer erstellt, welcher durch an/abschalten im LayerTree schließlich die initiale Geometrie + das neue Polygon sichtbar macht.

# Vermutung
Es könnte sich um eine verzwickte Reihenfolge der getriggerten Events handeln.

**Comment by Rastopapola** [comment]
# Bad Bugfix
Ich konnte mit folgenden Änderungen an `MapOpenLayers.js`, Z.393 ff. das oben beschriebene Verhalten korrigieren:

```javascript

netgis.MapOpenLayers.prototype.clearAll = function()
{
	for ( var i = 0; i < this.layers.length; i++ )
	{
		if(this.layers[i] === this.editLayer){
			continue;
		};
		this.map.removeLayer( this.layers[ i ] );
	}
	
	this.layers = [this.editLayer];
	
	this.snapFeatures.clear();
	this.snapFeatures.push(this.editLayer);
};
```

Ist wahrscheinlich nicht schön oder im Sinne des Erfinders, aber kann sicherlich als Hilfestellung für einen sauberen Bugfix dienen.

# Bestehendes Problem
Zwar funktioniert hiermit die Darstellung initialer Geometrie wieder wie erwartet, allerdings wird im erneuten Bearbeitungsmodus einer initial geladenen Geometrie im LayerTree der entsprechende "Zeichnung" Ordner nicht angezeigt und auch nicht neu angelegt, sobald eine Änderung an der Geometrie, bspw. durch ein weiteres Polygon, vorgenommen wird. Hier wären wahrscheinlich auch Änderungen an `LayerTree.js` notwendig.

**Comment by Rastopapola** [comment]
# Bad Commit?
https://github.com/sebastianpauli/netgis-client/commit/1ae85bf8516a4d5274d7348d103bc22f721f6c78#diff-72d9bb2fe65a3c13800e34410570778c507666f6c6b7dfb18022a1f0593f25c6L1138-L1146

Hier wurde die Funktion zum initialen Laden vollständig ersetzt. Der neue Code sieht aber eher nach Debug Resten des zugehörigen Import Fixes aus? Wird dieser Code Snippet wieder auf den Ursprungszustand resetted funktioniert auch das initiale Laden von Geojson aus dem hidden input.

**Comment by sebastianpauli** [comment]
Kannst du bestätigen, dass das Problem weiter besteht?

Nach meinem letzten [Commit](https://github.com/sebastianpauli/netgis-client/commit/1ae85bf8516a4d5274d7348d103bc22f721f6c78#diff-72d9bb2fe65a3c13800e34410570778c507666f6c6b7dfb18022a1f0593f25c6L1138-L1146) funktioniert das z.B. mit folgender initialer Geometrie:

```HTML
<input type="hidden" id="netgis-storage" name="output" value='{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[334608.03579322767,5496181.287892353],[285132.2891174876,5535273.235883061],[315062.0617978736,5573754.372186414],[409737.87333787006,5516948.885262416],[334608.03579322767,5496181.287892353]]]},"properties":null}],"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::25832"}}}' />
```

In dem Commit habe ich `netgis.MapOpenLayers.prototype.onEditFeaturesLoaded` geändert, damit das auch über `createLayerGeoJSON` läuft (wie beim Import).

Wenn möglich Bitte fehlerhaftes Input-Value anhängen, damit ich mir das genauer anschauen kann.

**Comment by Rastopapola** [comment]
@sebastianpauli 

Zum ursprünglichen Problem des Issues: Die Ebene "Zeichnung" wird im aktuellsten Stand zwar beim initialen Laden einer Geometrie im ReadOnly Modus jetzt angelegt und augenscheinlich auch mit "etwas" gefüllt, dieses "etwas" sieht aber nach falsch transformierten Koordinaten aus. Im hiddenInputt steht dann als value folgendes:
```geojson
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[500000.0000000001,9997964.942938771],[500000.00000000023,9997964.942938771],[500000.00000000023,9997964.942938771],[500000.0000000003,9997964.942938771],[500000.0000000003,9997964.942938771],[500000.0000000003,9997964.942938771],[500000.0000000003,9997964.942938771],[500000.0000000003,9997964.942938771],[500000.0000000003,9997964.942938771],[500000.00000000023,9997964.942938771],[500000.00000000023,9997964.942938771],[500000.0000000002,9997964.942938771],[500000.0000000001,9997964.942938771],[500000.00000000006,9997964.942938771],[500000.00000000006,9997964.942938771],[499999.99999999994,9997964.942938771],[500000,9997964.942938771],[499999.9999999999,9997964.942938771],[499999.99999999977,9997964.942938771],[499999.99999999977,9997964.942938771],[499999.99999999977,9997964.942938771],[499999.9999999997,9997964.942938771],[499999.99999999965,9997964.942938771],[499999.99999999965,9997964.942938771],[499999.9999999997,9997964.942938771],[499999.9999999998,9997964.942938771],[499999.9999999999,9997964.942938771],[499999.9999999999,9997964.942938771],[500000,9997964.942938771],[500000,9997964.942938771],[499999.99999999994,9997964.942938771],[499999.99999999994,9997964.942938771],[499999.9999999999,9997964.942938771],[499999.9999999999,9997964.942938771],[499999.99999999977,9997964.942938771],[499999.99999999977,9997964.942938771],[499999.99999999977,9997964.942938771],[499999.9999999998,9997964.942938771],[499999.9999999999,9997964.942938771],[499999.99999999994,9997964.942938771],[499999.9999999999,9997964.942938771],[500000,9997964.942938771],[500000.00000000006,9997964.942938771],[500000.0000000001,9997964.942938771],[500000.0000000001,9997964.942938771],[500000.0000000001,9997964.942938771]]]},"properties":null}],"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::25832"}}}
```
Hierbei handelt es sich um dieselbe Geometrie, die du zum Testen von mir geschickt bekommen hattest. 

Es scheint jetzt also nur noch um irgendeinen Bug beim Auslesen/Transformieren einer initialen Geometrie zu gehen.

**Comment by Rastopapola** [comment]
Verwendetes geojson wurde optimiert. Issue wird damit geschlossen.
