### ISSUE TITLE
[Bug] Initiale Geometrie wird nicht geladen 

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#12]
# Bisher 
Bisher konnte einfach mittels geojson in das hidden input Feld des Kartenclients eine Geometrie übergeben werden, welche beim initialen Öffnen angezeigt werden soll. 

Beispiel:
```html
<input type="hidden" id="netgis-storage" name="geom" value='{"type": "FeatureCollection", "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:EPSG::25832"}}, "features": [{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[381350.459734964, 5562267.21049383], [381369.934043284, 5562172.25981397], [381553.722828051, 5562149.13080221], [381472.174161962, 5562287.90487278], [381425.922679703, 5562290.9481638], [381350.459734964, 5562267.21049383]]]}}]}'">
```

Im neuen Client scheint das initiale Laden aber nicht zu funktionieren:
![grafik](https://github.com/sebastianpauli/netgis-client/assets/35961376/c2365eaf-20ef-49d3-a94c-a8cff47b4c96)

Die Konsole wirft leider keine Fehlermeldung aus.

**Comment by Rastopapola** [comment]
# Update
Das initiale Laden ist mit der Version 20231120 gefixt, allerdings ist die defaultmäßige Zoomstufe deutlich niedriger als zuvor:
![grafik](https://github.com/sebastianpauli/netgis-client/assets/35961376/cb0829e8-625c-4ec7-9215-e481eb775f04)

Lässt sich das per Konfiguration einstellen?

**Comment by sebastianpauli** [comment]
Funktioniert nun wieder in der aktuellen Version 20231121 (es gab ein Problem mit dem initialen OL Map Extent).
