### ISSUE TITLE
Karte verschieben während Eckpunkt-verschieben

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#13]
# Status quo
Aktuell ist es nicht möglich den Kartenausschnitt weiter zu verschieben, während das Eckpunkt-Verschieben Tool aktiv ist. Das ist eine wichtige Komfortfunktion, die auch bereits von Nutzern angefragt worden ist.

**Comment by Rastopapola** [comment]
Wurde bereits durch mittlere Maustaste in 03/2023 implementiert:
https://github.com/sebastianpauli/netgis-client/commit/6ed0dd8ec83d2968e0a19f7b10416c984cf984fd

>- allow panning while vertex editing (middle mouse button)

**Comment by sebastianpauli** [comment]
Funktioniert nun auch mit der linken Maustaste (wenn nicht über einem Eckpunkt) in der aktuellen Version 20231121 (coming to the repo soon...).
