### ISSUE TITLE
Config mit keys statt indizes

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#16]
# Status quo
Aktuell werden parent-child Beziehungen in der config durch indizes ermöglicht:

```json
...
		{ "title": "ABC", "parent": -1 },
		{ "title": "DEF", "parent": -1 },
		{ "title": "GHI", "parent": -1 },
		{ "title": "JKL", "parent": -1 },
		{ "title": "MNO", "parent": 2 },
		{ "title": "PQR", "parent": 4 },
		{ "title": "STU", "parent": 4 },
```

# Problem
Sobald sich die Reihenfolge der Einträge (der Übersichtlichkeit halber) ändert oder Elemente in der Mitte entfernt werden, muss die folgende Nummerierung neu erstellt werden.

# Idee
Sowohl für Layer als auch Gruppen könnte eine `id` eingeführt werden, welche das Element eindeutig identifiziert und zur Verlinkung in `parent` genutzt wird.
Bsp:
```json

		{ "id": "abc", "title": "ABC", "parent":  null },
		{ "id": "def",  "title": "DEF", "parent":  null },
		{ "id": "ghi",  "title": "GHI", "parent": null },
		{ "id": "jkl",  "title": "JKL", "parent": null },
		{ "id": "mno",  "title": "MNO", "parent": "def" },
		{ "id": "pqr",  "title": "PQR", "parent": "jkl" },
		{ "id": "stu",  "title": "STU", "parent": "jkl" },
```

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

Folder and Layer items in the config are now referenced by self-defined ID strings.

Example:

```
{ "id": "osm", "folder": "bg", "type": "OSM", "title": "Open Street Map", "attribution": "OSM", "active": true, "order": 1, "min_zoom": 1, "max_zoom": 20 }
```
