### ISSUE TITLE
Read-only Modus

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#17]
# Status quo

In der neuesten Version (20231206)  hat das `read-only` Argument keinen Effekt mehr.

# Fix
Sofern `data-editable="false"` im `<main>` Element gesetzt ist, soll

* das Menü Werkzeuge versteckt sein
* das Auswählen eines Flurstücks der Flurstücksuche (sowohl aus der Liste als auch per Klick in die Karte) keine Geometrie in die Karte zeichnen

**Comment by sebastianpauli** [comment]
Should be fixed in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).
