### ISSUE TITLE
Exportiere Geometrie

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#18]
# Status quo
Das Werkzeug `Exportieren` ermöglicht das Abspeichern des aktuellen Kartenausschnitts als Bild. 

# Verbesserung
Neben den Bilddateien soll ein Export als Geometriedatei ebenfalls möglich sein. Mindestens `geojson` soll auswählbar sein. **Man muss darüber sprechen** wie aufwändig ein Export als `shape`, `geopackage` und `gml` zusätzlich wäre.

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

In the toolbox you can open the Export Window which has a GeoJSON tab (next to the image formats) to export the drawing geometries to a file for downloading.

You can then also specify to include non-editable geometries or not.

![grafik](https://github.com/user-attachments/assets/9e2e9428-b26a-4e33-bfaa-6b109330df78)

**Comment by Rastopapola** [comment]
Fantastic!
