### ISSUE TITLE
Config mit radio buttons

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#19]
# Status quo
Alle Layer und gruppierende Oberelemente können mittels Checkbox angewählt werden. Gerade bei Hintergrundkarten ist das aber nicht unbedingt gewünscht, da sie einander vollständig überlagern.

# Verbesserung
Die Checkbox soll der Standard bleiben, sofern nichts anderes spezifiziert wurde. Der Konfiguration eines folders soll mitgegeben werden können, ob dieser (und sämtliche Kinder darin) durch einen Radio Button eingestellt werden können:

* Der so konfigurierte folder kann nicht mehr mittels Checkbox aktiviert werden
* Alle darin befindlichen folder können ebenfalls nicht mehr mittels Checkbox aktiviert werden
* Erst die leafs (die tatsächlichen Kartenebenen) können mittels Radiobutton aktiviert werden
* Wird innerhalb einer solchen Gruppe eine andere Kartenebene gewählt, wechselt die Auswahl von der ersten Ebene zu dieser, sodass immer nur eine Kartenebene aktiviert sein darf.

## Beispielkonfiguration
```json

	"folders":
	[
		{ "title": "ABC", "parent": -1 },
		{ "title": "DEF", "parent": -1, "singleLayer": true },
		{ "title": "GHI", "parent": -1, "singleLayer": false },
      ]
```

In dieser Beispielkonfiguration würden sich `ABC` und `GHI` identisch verhalten und die gewohnte Checkbox rendern. `DEF` hingegen würde das oben beschriebene Radiobuttonverhalten triggern.

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

Folder items in the Layer Tree config can now have a "radio" parameter.

Example:

```
{ "id": "bg", "title": "Hintergrund", "parent": null, "radio": true }
```

![grafik](https://github.com/user-attachments/assets/28c4935e-818e-4f70-bc89-08bf15b935f0)
