### ISSUE TITLE
Visual improvements on geometry area rendering

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#2]
An idea for a more pleasing visualization:

# Util.js
l. 166: Increase threshold for 'large' geometries, add thousand separator and use km² and m².
```javscript
                        ...
			var large = ( area > 100000 );
                        ...
			// Build String
			i = i.toLocaleString("de-DE")
			output = i + ( large ? " km²" : " m²" );
```

**Comment by sebastianpauli** [comment]
Fixed in [latest commit](https://github.com/sebastianpauli/netgis-client/commit/2014ac31ad371ad660a25f25604cf5fec3b4ba16).
