### ISSUE TITLE
Schieberegler Transparenz

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#22]
# Status quo
Eine Kartenebene kann aktiviert werden und ist mit der vorgegebenen Transparenz ein- bzw. ausschaltbar. 

# Enhancement
An jeder Kartenebene (Nur den leafs im Ebenenbaum) soll ein Schieberegler die Transparenz der Ebene steuern können. 

## Zu beachten:
Die Hover Funktion des Cursors aktiviert die Checkbox auf ganzer Breite des Elements (grundsätzlich sehr komfortabel):
![layer](https://github.com/sebastianpauli/netgis-client/assets/35961376/9c427b58-ce6f-48e1-9a92-72e26e8f443f)

Damit das Verstellen des Schiebereglers nicht mit dem Anklicken der Ebene interferiert, sollte die trigger-sensitive Box lediglich Checkbox und Namen der Ebene umfassen. Dahinter ist dann ein Bereich frei (von Cursorinterkation, die die Ebene triggert), die für den Schieberegler genutzt werden kann. 

Denkbar wäre daher etwas derartiges:
![layer_neu](https://github.com/sebastianpauli/netgis-client/assets/35961376/2003fa7d-d77a-4df7-b5d8-be75e7e0bd24)

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

Layer items in the Layer Tree now have a Transparency Slider if you expand the dropdown on the right.

![grafik](https://github.com/user-attachments/assets/4fa61742-5065-4c47-ba6c-f5d59c50899a)

**Comment by Rastopapola** [comment]
Sehr schön - nichts zu meckern!
