### ISSUE TITLE
Snapping configuration

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#23]
# Status quo
In der Konfiguration lassen sich Standardeinstellungen für Werkzeuge hinterlegen. Aktuell gibt es nur Einstellungen für das Buffern: 

```json
...
	"tools":
	{
		"buffer":
		{
			"defaultRadius": 5,
			"defaultSegments": 2
		}
	},
...
```

# Enhancement
Die Konfiguration sollte um einen Block für Snapping Standardwerte erweitert werden:

```json
...
	"tools":
	{
		"buffer":
		{
			"defaultRadius": 5,
			"defaultSegments": 2
		},
		"snapping":
		{
			"defaultToggled": true,
			"defaultPixelTolerance": 10
		}
	},
...
```

### defaultToggled
Dieser Wert bestimmt, ob das Snapping standardmäßig de-/aktiviert sein soll (true -> aktiviert; false -> deaktiviert).

### defaultPixelTolerance
Dieser Wert bestimmt wie stark der "magnetische Effekt" des Snapping sein soll. (vgl. [OpenLayers Dokumentation](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Snap-Snap.html))

## PixelTolerance Frontend
Der Nutzer soll auch in der Lage sein die pixelTolerance einstellen zu können. Hier wäre ein stufenlos verstellbarer Schieberegler die nutzerfreundlichste Variante. 
Als Label für das Attribut könnte einfach "Intensität" verwendet werden. Ein voll ausgeschlagener Schieberegler ist dann als "sehr intensives Snapping" besser verständlich als ein "sehr tolerantes Snapping".

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

Example:

```
"tools":
{				
	"snapping":
	{
		"show": true,
		"active": true,
		"tolerance": 10
	}
}
```

**Comment by Rastopapola** [comment]
Works fine, thanks!
