### ISSUE TITLE
Hinzufügen weiterer Dienste funktioniert nicht immer

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#24]
# Status quo

In einigen Fällen können die Dienste scheinbar nicht korrekt geparsed werden. 

https://geodaten.naturschutz.rlp.de/kartendienste_naturschutz/mod_ogc/wfs_getmap.php?mapfile=kom_recorded&service=WFS&Request=GetCapabilities
![grafik](https://github.com/sebastianpauli/netgis-client/assets/35961376/9d2e2fe4-a1ae-4b98-8371-5378bc23f613)

Andere wiederum funktionieren:
https://geo5.service24.rlp.de/wms/RLP_VBORISFREE2022.fcgi?REQUEST=GetCapabilities&VERSION=1.1.1&SERVICE=WMS

Aber auch hier wiederum: Wird derselbe Dienst (VBORIS) über die Geoportal URL aufgerufen, funktioniert er nicht:
https://www.geoportal.rlp.de/mapbender/php/mod_showMetadata.php/../wms.php?layer_id=32937&PHPSESSID=0hjqdl0tdrnu75vd1dc5iqb9ub&REQUEST=GetCapabilities&VERSION=1.1.1&SERVICE=WMS&withChilds=1

**Comment by sebastianpauli** [comment]
Should be fixed in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

Please test again with problematic services.
