### ISSUE TITLE
Startpunkt und -zoom übergeben

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#25]
# Status quo
Dem Kartenclient wird eine initiale Geometrie als geojson übergeben. Sofern keine Geometrie angegeben wird, zoomt die Karte auf die Standardwerte der Konfiguration.

# Enhancement
Es wäre praktisch, wenn neben dem Standardwert der Konfiguration (als fallback) ein priorisierter Startpunkt und Zoomstufe angegeben werden könnten. Diese könnten dem HTML als Attribute hinzugefügt werden und vom Kartenclient beim Start ausgelesen werden, so wie bereits das Attribut `data-editable` eingesetzt wird. 

Bsp.:
* **data-lon**: Enthält den Längengrad
* **data-lat**: Enthält den Breitengrad
* **data-zoom**: Enthält die Zoomstufe
```html

<main id="container" data-editable="true" data-lat="55.1234" data-lon="7.01234" data-zoom="15" style="position: relative; width: 100%; height: 100%;">
</main>
```

Falls eines der Attribute nicht angegeben wird, soll der Standardwert der Konfiguration gewählt werden. Ist eine Geometrie vorhanden, soll wiederum die Positionsangabe des HTML ignoriert werden und der Viewport an der Geometrie ausgerichtet werden. 

Es ergibt sich also folgende Priorisierung der Angaben von niedrig nach hoch:

Config  >>  HTML  >>  Geometrie

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

Example:
`<main id="container" data-lon="7.0" data-lat="50.0" data-zoom="12"></main>`

**Comment by Rastopapola** [comment]
>Falls eines der Attribute nicht angegeben wird, soll der Standardwert der Konfiguration gewählt werden. Ist eine Geometrie vorhanden, soll wiederum die Positionsangabe des HTML ignoriert werden und der Viewport an der Geometrie ausgerichtet werden.

In der neuesten Version kann der Startpunkt des Viewports zwar definiert werden aber 
* der in der config angegebene Wert (in `map.center_lonlat` definiert) wird scheinbar nicht als fallback genutzt  
* wenn im hidden input Element eine Geometrie mitgegeben wird, zoomt der Viewport nicht auf die Geometrie

Bitte nochmal das Issue öffnen, damit wir eine bessere Übersicht haben wo noch was zu tun ist.
