### ISSUE TITLE
Einzelimport aus Sammeldatei

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#27]
# Status quo
Aktuell wird sämtliche Geometrie einer Datei in den Kartenclient importiert. Es gibt allerdings Fälle, in denen speichern Nutzer "alle" Geometrien in einer Datei ab, wollen aber nur einzelne Geometrien hiervon im Kartenclient verwenden.

# Enhancement
Sobald eine Datei mittels "Hinzufügen" ausgewählt wird, soll diese sofort vom Kartenclient eingelesen aber noch nicht angezeigt werden. Der "Import" Dialog bleibt geöffnet. Unterhalb des "Hinzufügen" Elements öffnet sich eine kleine Tabelle, die folgenden Aufbau hat:

| Importieren  | ID | Fläche |
| -------- | ------- | -- |
| [x]  | 1    | 750m² |
| [ ] | 2     | 1200m² |
| [x]    | 3    | 500m² |

Durch Setzen der Checkboxen können einzelne Geometrien der Datei für den Import gewählt werden. Je nach Datentyp könnten IDs bereits mitgeliefert werden (bspw. bei Shape). In diesem Fall sollen diese IDs bevorzugt zur Darstellung genutzt werden. Falls keine ID oder anderer beschreibender Identifikator an den einzelnen Geodatensätzen hängt, soll eine fortlaufende Nummerierung gewählt werden. Dann muss der Nutzer über die jeweiligen Flächengrößen entscheiden, welche Fläche hinzugefügt werden soll. 

Erst wenn die Checkboxen gesetzt sind, wird das Bestätigen des Import Dialogs die gewählten Geometrien in die Karte übernehmen.

# Optimierung
Der oben beschriebene Ansatz weist sicherlich Schwachstellen in spezifischen Grenzfällen auf. Rückmeldung und Diskussion hierzu sind erwünscht.

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

After selecting a file to import, a Preview Window will open to select which features to add:

![grafik](https://github.com/user-attachments/assets/5d017409-6f22-483c-a968-d9fa19a04ba7)
