### ISSUE TITLE
Eckpunkt Verschieben mit Snapping

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#28]
# Status quo
Beim `Verschieben` ist es derzeit nicht möglich Snapping zu nutzen.

# Enhancement
Gleiche `Snapping` Option bei `Verschieben` bieten wie bereits beim Zeichnen von Polygonen.

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

The Move Vertex tool now also has a snapping option like the draw tools.

**Comment by Rastopapola** [comment]
Yes, works nicely.

# Hint to bug
If the setting `tools.snapping.active` is set to `true` in the config (making this setting activated on startup), the snap does not work. It needs to be toggled off and then on again, to fully work. ("Hello IT, have you tried turning it off and on again" :D)
