### ISSUE TITLE
[Bug] Punkte verschwinden bei Hover

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#30]
# Status quo

Punkte in der Karte werden unsichtbar, wenn sie mit den Funktionen `Löschen`, `Puffern` oder `Ausschneiden` berührt werden. Das Hover-blau-Leuchten scheint sie unsichtbar zu machen, anstatt sie blau zu markieren. Die Punkte bleiben im Anschluss unsichtbar.

Trifft nicht auf Linien und Polygone zu.

![netgis_map_point_disappearing_bug](https://github.com/user-attachments/assets/06245507-f3df-4970-a1e6-e19b59ca05ff)

**Comment by sebastianpauli** [comment]
Fixed in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

**Comment by Rastopapola** [comment]
Bestätige, Bug gefixt!
