### ISSUE TITLE
WFS format configurable

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#6]
# Status quo
Ein WFS versucht stets `application/json` anzufordern, wobei es Dienste gibt, die auf bspw. `application/json geojson` o.ä. anspringen. Hier würde ebenfalls das erwartete json zurückgeliefert werden.

# Feature
Es sollte noch eine Möglichkeit für die `config.json` geben, dass das anzufragende Format vorab definiert werden kann. Falls kein Format angegeben wird, soll der default `application/json` verwendet werden.

**Comment by sebastianpauli** [comment]
Sollte nun funktionieren, indem in der Layer-Config der Wert "format" auf den gewünschten MIME-Type gesetzt wird, z.B. `"format": "application/json geojson"`.
Dieser Wert wird dann weitergereicht an die WFS-Requests.
