### ISSUE TITLE
Flächengrößenanzeige in Fläche an Viewport orientieren

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#7]
# Status quo
Die Flächengrößenanzeige in einer Fläche wird zentriert zu den Ausmaßen der Fläche dargestellt. Das führt zu Darstellungsproblemen, wenn es sich um eine sehr lange, schmale Fläche handelt oder eine andersartige, in welcher dieser Darstellungspunkt nicht innerhalb der eigentlichen Fläche liegt (dann wird nichts gerendert).

# Enhancement
Es wäre besser, wenn die Flächenmenge eines Features so gerendert wird, dass sie sich innerhalb des Features, jedoch relativ zum Viewport des Clients verhält und somit bspw. auch entlang einer langen, schmalen Fläche "mitwandert".

**Comment by sebastianpauli** [comment]
Added in latest [LANIS Update](https://github.com/sebastianpauli/netgis-client/commit/81fa3bef489b589c9e8252277923ce7012e07093).

If a vector style in the config has the "viewport_labels" set to true, labels will now try to stay inside of the viewport extent.

Example:

```
"styles":
{
	"draw":
	{
		"fill": "rgba( 255, 0, 0, 0.5 )",
		"stroke": "#ff0000",
		"width": 3,
		"radius": 6,
		"viewport_labels": true
	}
}
```

This example shows the label offset from the center of a circle geometry to stay inside the view:

![grafik](https://github.com/user-attachments/assets/5bfa718b-d62d-4441-ae07-2c1259c637c4)
