### ISSUE TITLE
Gesamtflächeninhalt rendern

### ISSUE THREAD

**Issue by Rastopapola** [sebastianpauli/netgis-client#8]
# Status quo
Aktuell wird der Gesamtflächeninhalt in der Kartenebene der "Zeichnung" dargestellt. Für viele Nutzer ist das jedoch zu versteckt und nicht intuitiv auffindbar.

# Enhancement
Stattdessen könnte die Gesamtfläche in der oberen linken Ecke des Kartenbildes (mit passendem, gut kontrastiertem Farbschema) dargestellt werden. Wenn ein Menü von oben geöffnet wird und die Anzeige überlappen würde, wird die Anzeig ausreichend nach unten verschoben, um trotzdem sichtbar zu bleiben.

**Comment by sebastianpauli** [comment]
Semi-fixed in [latest commit](https://github.com/sebastianpauli/netgis-client/commit/2014ac31ad371ad660a25f25604cf5fec3b4ba16) by outputting the area size at the end of the bottom attributions.

May be moved to seperate similar info panel in the near future.

**Comment by Rastopapola** [comment]
Looks fine
![grafik](https://github.com/sebastianpauli/netgis-client/assets/35961376/8507b000-6445-42f7-86d0-aa0734167095)

Moving to another position can be discussed.
